### ISSUE TITLE
Args 5, 5 Causes Error

### ISSUE THREAD

**Issue by kpit-rjma** [dflynt/PythonMicroProject#2]
When running the program, using width and heights of 5 (should be smallest acceptable) causes an error.

```
rachela@USL-1302 MINGW64 ~/Documents/Git/PythonMicroProject (dev)
$ python game.py 5 5
Traceback (most recent call last):
  File "game.py", line 84, in <module>
    game.createBoundaries()
  File "game.py", line 38, in createBoundaries
    self.board[2][x] = " 0 "
IndexError: list assignment index out of range
```

**Comment by pmessina** [comment]
See if arguments more than 5 works.

**Comment by dflynt** [comment]
Board dimensions are now set at a fixed 10, 10 in the Game constructor, line 76
